CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_IOL_MASTER=y
CONFIG_IOL_MASTER_NUM_CHANNELS=1
CONFIG_IOL_MASTER_STACK_SIZE=4096
CONFIG_IOL_MASTER_TASK_PRIORITY=4
CONFIG_IOL_DL_STACK_SIZE=2048
CONFIG_IOL_DL_TASK_PRIORITY=5
CONFIG_HEAP_MEM_POOL_SIZE=65536
CONFIG_EVENTS=y
CONFIG_MULTITHREADING=y
CONFIG_KERNEL_MEM_POOL=y

CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3
